const cnjson = {
    'how to manage HTML DOM': '如何操作HTML DOM',
    'for modern browsers and IE 11+': '适用于现代浏览器和ie11 +',
    'Add or remove class from an element': '从元素中添加或删除class ',
    'Allow to enter particular characters only': '只允许输入特定字符',
    'Append to an element': '追加元素',
    'Attach or detach an event handler': '添加或删除绑定的事件',
    'Calculate the mouse position relative to an element': '计算鼠标相对于元素的位置',
    'Calculate the size of scrollbar': '计算滚动条的大小',
    'Change the website favicon': '改变网站favicon',
    'Check an element against a selector': '根据选择器检查元素',
    'Check if an element has given class': '检查元素是否有指定的class',
    'Check if an element is a descendant of another': '检查一个元素是否是另一个元素的后代',
    'Check if an element is in the viewport': '检查一个元素是否在视图中',
    'Check if an element is scrollable': '检查元素是否可滚动',
    'Check if the native date input is supported': '检查是否支持本机日期输入',
    'Clone an element': '克隆一个元素',
    'Communication between an iframe and its parent window': 'iframe与其父窗口之间的通信',
    'Copy text to the clipboard': '将文本复制到剪贴板',
    'Count the number of characters of a textarea': '计算文本区域的字符数',
    'Create an element': '创建一个元素',
    'Create one time event handler': '创建一次性事件处理程序',
    'Detect clicks outside of an element': '检测元素外的点击',
    'Detect if an element is focused': '检测一个元素是否被聚焦',
    'Detect if the caps lock is on': '检测大写锁定是否打开',
    'Detect mac os browser': '检测mac os浏览器',
    'Determine the height and width of an element': '确定元素的高度和宽度',
    'Distinguish between left and right mouse clicks': '区分鼠标左键和右键点击',
    'Download a file': '下载文件',
    'Drag and drop element in a list': '在列表中拖放元素',
    'Drag and drop table column advanced': '拖放表列前进',
    'Drag and drop table column': '拖放table column',
    'Drag and drop table row': '拖放table row',
    'Execute code when the document is ready': '当文档准备好时执行代码',
    'Export a table to csv': '将table导出为csv',
    'Get css styles of an element': '获取元素的css样式',
    'Get or set the document title': '获取或设置文档标题',
    'Get or set the html of an element': '获取或设置元素的html',
    'Get set and remove attributes': '获取设置和删除属性',
    'Get set and remove data attributes': '获取并删除数据属性',
    'Get siblings of an element': '得到元素的兄弟元素',
    'Get size of the selected file': '获取所选文件的大小',
    'Get the closest element by given selector': '通过给定的选择器获得最近的元素',
    'Get the default value of a css property': '获取css属性的默认值',
    'Get the document height and width': '获取文档的高度和宽度',
    'Get the first scrollable parent of an element': '获取元素的第一个可滚动的父元素',
    'Get the parent node of an element basic': '获取一个元素的父节点',
    'Get the parent node of an element': '获取元素的父节点',
    'Get the position of an element relative to another': '获取一个元素相对于另一个元素的位置',
    'Get the position of an element relative to the document': '获取元素相对于文档的位置',
    'Get the size of an image': '获取图像的大小',
    'Get the text content of an element': '获取元素的文本内容',
    'Go back to the previous page': '回到前一页',
    'Highlight an element when dragging a file over it': '拖动文件时突出显示元素',
    'Insert an element after or before other element': '在元素之后或之前插入一个元素',
    'Insert given html after or before an element': '在元素之后或之前插入给定的html',
    'Load a css file dynamically': '动态加载css文件',
    'Load a javascript file dynamically': '动态加载javascript文件',
    'Loop over a nodelist': '循环一个节点列表',
    'Make a draggable element': '创建一个可拖动的元素',
    'Make a resizable element': '创建一个可调整大小的元素',
    'Measure the width of given text of given font': '测量特定的文本的宽度',
    'Paste an image from the clipboard': '从剪贴板粘贴一个图像',
    'Paste as plain text': '粘贴为纯文本',
    'Placeholder for a contenteditable element': '一个可写元素的占位符',
    'Prepend to an element': '预加载元素',
    'Press shift and enter for a new line': '按shift键并输入一个新行',
    'Prevent the default action of an event': '阻止事件的默认操作',
    'Preview an image before uploading it': '在上传图片之前先预览它',
    'Put cursor at the end of an input': '将光标放在input的末尾',
    'Redirect to another page': '重定向到另一个页面',
    'Reload the current page': '重新加载当前页面',
    'Remove all children of a node': '删除节点的所有子节点',
    'Remove an element': '删除一个元素',
    'Replace an element': '替换一个元素',
    'Replace broken images': '更换加载异常的图片',
    'Resize an iframe to fit its content': '调整iframe的大小以适应其内容',
    'Resize an image': '调整图像大小',
    'Resize columns of a table': '调整表的列的大小',
    'Resize the width of a text box to fit its content automatically': '自动调整文本框的宽度以适应其内容',
    'Scale a text to fit inside of an element': '缩放文本以适应元素大小',
    'Scroll to top of the page': '滚动到页面顶部',
    'Select an element or list of elements': '选择一个或多个元素',
    'Select the children of an element': '选择元素的子元素',
    'Select the text of a textarea automatically': '自动选择textarea的文本',
    'Serialize form data into a query string': '将form data序列化为字符串',
    'Set css style for an element': '设置元素的css样式',
    'Show a ghost element when dragging an element': '拖动元素时保持显示此元素的占位元素',
    'Show or hide an element': '显示或隐藏元素',
    'Sort a table by clicking its headers': '通过单击表的标题对表进行排序',
    'Strip html from a given text': '从文本中取出其中的html',
    'Submit a form with ajax': '使用ajax提交表单',
    'Swap two nodes': '交换两个节点',
    'Toggle an element': '切换一个元素',
    'Toggle password visibility': '切换密码可见性',
    'Trigger an event': '触发一个事件',
    'Unwrap an element': '打开一个元素',
    'Upload files with ajax': '使用ajax上传文件',
    'Wrap an element around a given element': '将一个元素包在另一个元素上',
    'Hit the Subscribe button for the latest news on my tools. No spam. Ever!': '点击订阅按钮获取我的最新消息。没有垃圾邮件!',
    'Subscribe': '订阅',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',
    'sssssssss': '',


}