import Post from './Post';

const PostList: Post[] = [
    { slug: 'add-or-remove-class-from-an-element', category: 'Basic', slugZh: '向元素添加或是删除 class 属性', categoryZh: '基础' },
    { slug: 'allow-to-enter-particular-characters-only', category: 'Intermediate', slugZh: '只允许输入特定字符', categoryZh: '中级' },
    { slug: 'append-to-an-element', category: 'Basic', slugZh: '将内容附加到一个元素中', categoryZh: '基础' },
    { slug: 'attach-event-handlers-inside-other-handlers', category: 'Tip', slugZh: '将事件处理程序附加到其他处理程序中', categoryZh: '技巧' },
    { slug: 'attach-or-detach-an-event-handler', category: 'Basic', slugZh: '创建和删除一个事件处理', categoryZh: '基础' },
    { slug: 'calculate-the-mouse-position-relative-to-an-element', category: 'Basic', slugZh: '计算鼠标指正相对于元素的位置', categoryZh: '基础' },
    { slug: 'calculate-the-size-of-scrollbar', category: 'Intermediate', slugZh: '计算滚动条尺寸', categoryZh: '中级' },
    { slug: 'change-the-website-favicon', category: 'Intermediate', slugZh: '改变网站的 favicon 图标', categoryZh: '中级' },
    { slug: 'check-an-element-against-a-selector', category: 'Basic', slugZh: '根据选择器检查在元素中是否存在', categoryZh: '基础' },
    { slug: 'check-if-an-element-has-given-class', category: 'Basic', slugZh: '检查元素是否有指定的 class 属性值', categoryZh: '基础' },
    { slug: 'check-if-an-element-is-a-descendant-of-another', category: 'Basic', slugZh: '检查一个元素是否是另一个元素的子元素(后代)', categoryZh: '基础' },
    { slug: 'check-if-an-element-is-in-the-viewport', category: 'Basic', slugZh: '检查元素是否在可是界面中', categoryZh: '基础' },
    { slug: 'check-if-an-element-is-scrollable', category: 'Intermediate', slugZh: '检查元素是否能够滚动', categoryZh: '中级' },
    { slug: 'check-if-an-element-is-visible-in-a-scrollable-container', category: 'Intermediate', slugZh: '', categoryZh: '中级' },
    { slug: 'check-if-the-code-is-running-in-the-browser', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'check-if-the-native-date-input-is-supported', category: 'Basic', slugZh: '检查浏览器是否支持 H5 input 的 date 类型', categoryZh: '基础' },
    { slug: 'check-if-the-touch-events-are-supported', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'clone-an-element', category: 'Basic', slugZh: '复制元素', categoryZh: '基础' },
    { slug: 'communication-between-an-iframe-and-its-parent-window', category: 'Intermediate', slugZh: 'iframe 与父级 window 之间的通信', categoryZh: '中级' },
    { slug: 'copy-highlighted-code-to-the-clipboard', category: 'Advanced', slugZh: '', categoryZh: '高级' },
    { slug: 'copy-text-to-the-clipboard', category: 'Intermediate', slugZh: '将文字复制到粘贴板上', categoryZh: '中级' },
    { slug: 'count-the-number-of-characters-of-a-textarea', category: 'Basic', slugZh: '计算文本区域(textarea)的字符数', categoryZh: '基础' },
    { slug: 'create-a-custom-scrollbar', category: 'Advanced', slugZh: '', categoryZh: '高级' },
    { slug: 'create-a-range-slider', category: 'Advanced', slugZh: '创建一个区域滑块', categoryZh: '高级' },
    { slug: 'create-an-element', category: 'Basic', slugZh: '创建一个元素', categoryZh: '基础' },
    { slug: 'create-an-image-comparison-slider', category: 'Advanced', slugZh: '创建一个图像比较滑块', categoryZh: '高级' },
    { slug: 'create-one-time-event-handler', category: 'Basic', slugZh: '创建一次性的事件处理', categoryZh: '基础' },
    { slug: 'create-resizable-split-views', category: 'Advanced', slugZh: '创建可调整大小的拆分视图', categoryZh: '高级' },
    { slug: 'detect-clicks-outside-of-an-element', category: 'Basic', slugZh: '检测是否在元素外部的点击', categoryZh: '基础' },
    { slug: 'detect-if-an-element-is-focused', category: 'Basic', slugZh: '检测元素是否获得焦点', categoryZh: '基础' },
    { slug: 'detect-if-the-caps-lock-is-on', category: 'Intermediate', slugZh: '检测大写键是否打开', categoryZh: '中级' },
    { slug: 'detect-internet-explorer-browser', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'detect-mac-os-browser', category: 'Basic', slugZh: '检测所使用的浏览器是否是 Mac OS浏览器', categoryZh: '基础' },
    { slug: 'detect-mobile-browsers', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'detect-the-dark-mode', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'determine-the-height-and-width-of-an-element', category: 'Basic', slugZh: '获取一个元素的宽高', categoryZh: '基础' },
    { slug: 'distinguish-between-left-and-right-mouse-clicks', category: 'Basic', slugZh: '区分鼠标左键和右键', categoryZh: '基础' },
    { slug: 'download-a-file', category: 'Intermediate', slugZh: '下载一个文件', categoryZh: '中级' },
    { slug: 'drag-and-drop-element-in-a-list', category: 'Advanced', slugZh: '将元素拖拽到列表中', categoryZh: '高级' },
    { slug: 'drag-and-drop-table-column', category: 'Advanced', slugZh: '拖动表格行', categoryZh: '高级' },
    { slug: 'drag-and-drop-table-row', category: 'Advanced', slugZh: '拖动表格行', categoryZh: '高级' },
    { slug: 'drag-to-scroll', category: 'Advanced', slugZh: '', categoryZh: '高级' },
    { slug: 'execute-code-when-the-document-is-ready', category: 'Basic', slugZh: '等 HTML 元素(document 对象)准备好之后再运行代码', categoryZh: '基础' },
    { slug: 'export-a-table-to-csv', category: 'Intermediate', slugZh: '将表格导出为CSV文件', categoryZh: '中级' },
    { slug: 'get-css-styles-of-an-element', category: 'Basic', slugZh: '获取元素的 CSS 样式', categoryZh: '基础' },
    { slug: 'get-or-set-the-document-title', category: 'Basic', slugZh: '获取或是修改文档的标题(title 标签)', categoryZh: '基础' },
    { slug: 'get-or-set-the-html-of-an-element', category: 'Basic', slugZh: '获取一个元素的 HTML 内容', categoryZh: '基础' },
    { slug: 'get-set-and-remove-attributes', category: 'Basic', slugZh: '设置或是删除一个元素的属性(attribute)', categoryZh: '基础' },
    { slug: 'get-set-and-remove-data-attributes', category: 'Basic', slugZh: '设置或是删除一个元素的属性(attribute)数据', categoryZh: '基础' },
    { slug: 'get-siblings-of-an-element', category: 'Basic', slugZh: '获取一个元素的兄弟节点', categoryZh: '基础' },
    { slug: 'get-size-of-the-selected-file', category: 'Basic', slugZh: '取上传文件的大小', categoryZh: '基础' },
    { slug: 'get-the-closest-element-by-given-selector', category: 'Basic', slugZh: '通过给定 CSS 选择器获取最匹配的元素', categoryZh: '基础' },
    { slug: 'get-the-default-value-of-a-css-property', category: 'Intermediate', slugZh: '获取 CSS 属性的默认值', categoryZh: '中级' },
    { slug: 'get-the-direction-of-the-text-selection', category: 'Intermediate', slugZh: '', categoryZh: '中级' },
    { slug: 'get-the-document-height-and-width', category: 'Basic', slugZh: '获取文档(document 对象)的宽高', categoryZh: '基础' },
    { slug: 'get-the-first-scrollable-parent-of-an-element', category: 'Intermediate', slugZh: '获取元素的第一个可滚动父元素', categoryZh: '中级' },
    { slug: 'get-the-parent-node-of-an-element', category: 'Basic', slugZh: '获取元素的父级节点', categoryZh: '基础' },
    { slug: 'get-the-position-of-an-element-relative-to-another', category: 'Basic', slugZh: '获取一个元素相对于另一个元素的位置', categoryZh: '基础' },
    { slug: 'get-the-position-of-an-element-relative-to-the-document', category: 'Basic', slugZh: '获取一个元素相对于文档(document 对象)的位置', categoryZh: '基础' },
    { slug: 'get-the-selected-text', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'get-the-size-of-an-image', category: 'Basic', slugZh: '获取图片的大小', categoryZh: '基础' },
    { slug: 'get-the-text-content-of-an-element', category: 'Basic', slugZh: '获取元素的文本内容', categoryZh: '基础' },
    { slug: 'go-back-to-the-previous-page', category: 'Basic', slugZh: '返回上一个页面', categoryZh: '基础' },
    { slug: 'highlight-an-element-when-dragging-a-file-over-it', category: 'Intermediate', slugZh: '在进行文件拖动上传是高亮显示放置元素', categoryZh: '中级' },
    { slug: 'insert-an-element-after-or-before-other-element', category: 'Basic', slugZh: '在其他元素之前或之后插入一个元素', categoryZh: '基础' },
    { slug: 'insert-given-html-after-or-before-an-element', category: 'Basic', slugZh: '在其他元素之前或之后插入给定的 HTML 元素', categoryZh: '基础' },
    { slug: 'load-a-css-file-dynamically', category: 'Intermediate', slugZh: '动态添加 CSS 样式文件', categoryZh: '中级' },
    { slug: 'load-a-javascript-file-dynamically', category: 'Intermediate', slugZh: '动态添加 JavaScript 文件', categoryZh: '中级' },
    { slug: 'loop-over-a-nodelist', category: 'Basic', slugZh: '历遍节点列表', categoryZh: '基础' },
    { slug: 'make-a-draggable-element', category: 'Advanced', slugZh: '制作一个可拖动元素', categoryZh: '高级' },
    { slug: 'make-a-resizable-element', category: 'Advanced', slugZh: '制作一个调整大小元素', categoryZh: '高级' },
    { slug: 'measure-the-width-of-given-text-of-given-font', category: 'Intermediate', slugZh: '测量给定字体的给定文本的宽度', categoryZh: '中级' },
    { slug: 'paste-an-image-from-the-clipboard', category: 'Intermediate', slugZh: '从粘贴板粘贴图像', categoryZh: '中级' },
    { slug: 'paste-as-plain-text', category: 'Intermediate', slugZh: '粘贴为纯文本', categoryZh: '中级' },
    { slug: 'placeholder-for-a-contenteditable-element', category: 'Intermediate', slugZh: '一个可编辑元素的占位符', categoryZh: '中级' },
    { slug: 'position-an-element-absolutely-to-another-element', category: 'Intermediate', slugZh: '', categoryZh: '中级' },
    { slug: 'prepend-to-an-element', category: 'Basic', slugZh: '置顶某个元素', categoryZh: '基础' },
    { slug: 'press-shift-and-enter-for-a-new-line', category: 'Basic', slugZh: '实现按 Shift + Enter 键换行效果', categoryZh: '基础' },
    { slug: 'prevent-body-from-scrolling-when-opening-a-modal', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'prevent-the-default-action-of-an-event', category: 'Basic', slugZh: '阻止事件默认操作', categoryZh: '基础' },
    { slug: 'preview-an-image-before-uploading-it', category: 'Intermediate', slugZh: '', categoryZh: '中级' },
    { slug: 'print-an-image', category: 'Intermediate', slugZh: '打印图片', categoryZh: '中级' },
    { slug: 'put-cursor-at-the-end-of-an-input', category: 'Basic', slugZh: '将光标放置在输入的末尾', categoryZh: '基础' },
    { slug: 'redirect-to-another-page', category: 'Basic', slugZh: '重定向到另一个页面', categoryZh: '基础' },
    { slug: 'reload-the-current-page', category: 'Basic', slugZh: '重新加载当前页面', categoryZh: '基础' },
    { slug: 'remove-all-children-of-a-node', category: 'Basic', slugZh: '删除元素所有的子元素', categoryZh: '基础' },
    { slug: 'remove-an-element', category: 'Basic', slugZh: '删除元素', categoryZh: '基础' },
    { slug: 'replace-an-element', category: 'Basic', slugZh: '替换元素', categoryZh: '基础' },
    { slug: 'replace-broken-images', category: 'Basic', slugZh: '替换损坏的图片', categoryZh: '基础' },
    { slug: 'resize-an-iframe-to-fit-its-content', category: 'Basic', slugZh: '调整 iframe 大小以适应内容', categoryZh: '基础' },
    { slug: 'resize-an-image', category: 'Intermediate', slugZh: '调整图片大小', categoryZh: '中级' },
    { slug: 'resize-columns-of-a-table', category: 'Advanced', slugZh: '调整表格列的大小', categoryZh: '高级' },
    { slug: 'resize-the-width-of-a-text-box-to-fit-its-content-automatically', category: 'Intermediate', slugZh: '根据内容自动调整文本框的大小', categoryZh: '中级' },
    { slug: 'save-and-restore-the-text-selection', category: 'Intermediate', slugZh: '', categoryZh: '中级' },
    { slug: 'scale-a-text-to-fit-inside-of-an-element', category: 'Intermediate', slugZh: '根据可视内容大小调整文本缩放', categoryZh: '中级' },
    { slug: 'scroll-an-element-to-ensure-it-is-visible-in-a-scrollable-container', category: 'Intermediate', slugZh: '', categoryZh: '中级' },
    { slug: 'scroll-to-an-element', category: 'Basic', slugZh: '滚动到某一个元素', categoryZh: '基础' },
    { slug: 'scroll-to-an-element-smoothly', category: 'Advanced', slugZh: '滚动到页面顶部', categoryZh: '高级' },
    { slug: 'scroll-to-top-of-the-page', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'select-an-element-or-list-of-elements', category: 'Basic', slugZh: '选择一个元素或一个元素集合', categoryZh: '基础' },
    { slug: 'select-the-children-of-an-element', category: 'Basic', slugZh: '选择元素的子元素', categoryZh: '基础' },
    { slug: 'select-the-text-content-of-an-element', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'select-the-text-of-a-textarea-automatically', category: 'Basic', slugZh: '自动选择文本区域的文本', categoryZh: '基础' },
    { slug: 'serialize-form-data-into-a-query-string', category: 'Basic', slugZh: '将表单元素序列化为可查询字符串', categoryZh: '基础' },
    { slug: 'set-css-style-for-an-element', category: 'Basic', slugZh: '为元素设置内联 CSS 样式', categoryZh: '基础' },
    { slug: 'show-a-custom-context-menu-at-clicked-position', category: 'Intermediate', slugZh: '', categoryZh: '中级' },
    { slug: 'show-a-ghost-element-when-dragging-an-element', category: 'Intermediate', slugZh: '拖动一些元素时显示替换元素', categoryZh: '中级' },
    { slug: 'show-a-loading-indicator-when-an-iframe-is-being-loaded', category: 'Intermediate', slugZh: '当加载 iframe 时显示 loading 提示', categoryZh: '中级' },
    { slug: 'show-or-hide-an-element', category: 'Basic', slugZh: '显示或隐藏元素', categoryZh: '基础' },
    { slug: 'show-or-hide-table-columns', category: 'Advanced', slugZh: '', categoryZh: '高级' },
    { slug: 'sort-a-table-by-clicking-its-headers', category: 'Advanced', slugZh: '通过点击表头对表格进行排序', categoryZh: '高级' },
    { slug: 'strip-html-from-a-given-text', category: 'Basic', slugZh: '从给定文本中删除 HTML 标签', categoryZh: '基础' },
    { slug: 'submit-a-form-with-ajax', category: 'Basic', slugZh: '使用 Ajax 提交表单', categoryZh: '基础' },
    { slug: 'swap-two-nodes', category: 'Basic', slugZh: '交换两个节点元素', categoryZh: '基础' },
    { slug: 'toggle-an-element', category: 'Basic', slugZh: '切换元素', categoryZh: '基础' },
    { slug: 'toggle-password-visibility', category: 'Basic', slugZh: '切换密码是否可见', categoryZh: '基础' },
    { slug: 'trigger-an-event', category: 'Basic', slugZh: '触发事件', categoryZh: '基础' },
    { slug: 'unwrap-an-element', category: 'Basic', slugZh: '移动元素的子元素并删除该元素', categoryZh: '基础' },
    { slug: 'upload-files-with-ajax', category: 'Basic', slugZh: '', categoryZh: '基础' },
    { slug: 'wrap-an-element-around-a-given-element', category: 'Basic', slugZh: '使用 Ajax 上传文件', categoryZh: '基础' },
    { slug: 'zoom-an-image', category: 'Advanced', slugZh: '将已存在元素放置在给定元素中', categoryZh: '高级' },
];

export default PostList;
